version: '3'

services:

    db:
        image: 'postgres:13'
        container_name: 'online_store_db'
        ports:
            - 15432:5432
        environment:
            - 'POSTGRES_DB=store'
            - 'POSTGRES_USER=admin'
            - 'POSTGRES_PASSWORD=123'
