server:
    port: 8081

logging:
    level:
        com.example.demo: debug
    file:
        name: logs/dev.log

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:15432/store
        username: admin
        password: 123
    jpa:
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    liquibase:
        enabled: true
        change-log: classpath:db/changelog/db.changelog-master.yaml
