server:
    port: 8082

logging:
    level:
        com.example.demo: debug
    file:
        name: logs/app_debug.log

spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:online_store;MODE=PostgreSQL
        username: sa
        password:
    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true # web console: /h2-console
            settings:
                web-allow-others: false
